<div id="login" class="auth-form-container" style="display: none;">
    <form class="auth-form" action="auth/login.php" method="POST"><h2>Entrar</h2><div class="form-group"><label>E-mail</label><input type="email" name="email" required></div><div class="form-group"><label>Senha</label><input type="password" name="password" required></div><button class="auth-submit">Entrar</button><div class="auth-switch">Não tem conta? <a href="#" onclick="showSection('register')">Cadastre-se</a></div></form>
</div>

<div id="register" class="auth-form-container" style="display: none;">
    <form class="auth-form" action="auth/register.php" method="POST"><h2>Cadastro</h2><div class="form-group"><label>Nome</label><input type="text" name="name" required></div><div class="form-group"><label>E-mail</label><input type="email" name="email" required></div><div class="form-group"><label>Senha</label><input type="password" name="password" required></div><div class="form-group"><label>Confirmar</label><input type="password" name="confirm_password" required></div><button class="auth-submit">Cadastrar</button><div class="auth-switch">Já tem conta? <a href="#" onclick="showSection('login')">Entre</a></div></form>
</div>

<div id="columnModal" class="modal" style="display: none;">
    <div class="modal-content"><div class="modal-header"><h2>Nova Coluna</h2><span class="close-modal" onclick="closeColumnModal()">&times;</span></div><form action="columns/create.php" method="POST"><div class="form-group"><label>Nome da Coluna</label><input type="text" name="title" required placeholder="Ex: Revisão"></div><button type="submit" class="btn btn-primary" style="width: 100%;">Criar</button></form></div>
</div>

<div id="editColumnModal" class="modal" style="display: none;">
    <div class="modal-content"><div class="modal-header"><h2>Editar Coluna</h2><span class="close-modal" onclick="closeEditColumnModal()">&times;</span></div><form action="columns/update.php" method="POST"><input type="hidden" id="edit-col-id" name="id"><div class="form-group"><label>Nome da Coluna</label><input type="text" id="edit-col-title" name="title" required></div><div style="display: flex; gap: 10px; margin-top: 15px;"><button type="submit" class="btn btn-primary" style="flex: 1;">Salvar</button><a id="delete-col-btn" href="#" class="btn" style="background-color: #e74c3c; color: white; padding: 10px;">Excluir</a></div></form></div>
</div>

<div id="taskModal" class="modal" style="display: none;">
    <div class="modal-content"><div class="modal-header"><h2>Nova Tarefa</h2><span class="close-modal" onclick="closeTaskModal()">&times;</span></div><form action="tasks/create.php" method="POST"><div class="form-group"><label>Título</label><input type="text" name="title" required></div><div class="form-group"><label>Descrição</label><textarea name="description" rows="3"></textarea></div><div class="form-group" style="display: flex; gap: 15px;"><div style="flex: 1;"><label>Prazo</label><input type="date" name="deadline" required></div><div style="flex: 1;"><label>Prioridade</label><select name="priority" style="width:100%"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></div></div><button type="submit" class="btn btn-primary" style="width: 100%; margin-top: 15px;">Salvar</button></form></div>
</div>

<div id="editTaskModal" class="modal" style="display: none;">
    <div class="modal-content"><div class="modal-header"><h2>Detalhes</h2><span class="close-modal" onclick="closeEditModal()">&times;</span></div><form action="tasks/update.php" method="POST"><input type="hidden" id="edit-id" name="id"><div class="form-group"><label>Título</label><input type="text" id="edit-title" name="title" required></div><div class="form-group"><label>Descrição</label><textarea id="edit-desc" name="description" rows="3"></textarea></div><div class="form-group" style="display: flex; gap: 15px;"><div style="flex: 1;"><label>Prazo</label><input type="date" id="edit-deadline" name="deadline" required></div><div style="flex: 1;"><label>Prioridade</label><select id="edit-priority" name="priority" style="width:100%"><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></div></div><div class="form-group"><label>Mover para:</label><select id="edit-status" name="status" style="width: 100%; padding: 10px;"><?php foreach($columns as $col): ?><option value="<?php echo $col['id']; ?>"><?php echo htmlspecialchars($col['title']); ?></option><?php endforeach; ?></select></div><div style="display: flex; gap: 10px; margin-top: 15px;"><button type="submit" class="btn btn-primary" style="flex: 1;">Salvar</button><a id="delete-btn" href="#" class="btn" style="background-color: #e74c3c; color: white; padding: 10px;">Excluir</a></div></form></div>
</div>